workspace:
  base: /srv/app

clone:
  depth: 1

kind: pipeline
name: default

steps:
- name: deploy
  image: appleboy/drone-ssh
  pull: true
  settings:
    host: 
      from_secret: host
    port: 
      from_secret: port
    user:
      from_secret: user
    key:
      from_secret: ssh_key
  script:
  - bash /scripts/script-deploy.sh
  when:
    branch:
    - master
    event: 
    - push